version: '3.4'

x-mount-app-and-user-git-config: &mount-app-and-user-git-config
  volumes:
    - ./:/app
    - ~/.gitconfig:/home/gbq/.gitconfig # allow script to commit as user

services:

  # a fully loaded development environment to test new code
  devbox: &devbox
    build:
      dockerfile: ./docker/devbox.dockerfile
      context: .
    image: "wayfair/pygitops-devbox"
    volumes:
      - ./:/app
      - ~/.gitconfig:/home/pygitops/.gitconfig

  # run all the tests and linting locally
  # - black & isort will format code to address issues
  test:
    <<: *devbox
    command: docker/run_tests.sh --format-code

  # generate and serve the project documentation locally
  mkdocs: &mkdocs
    <<: *devbox
    entrypoint: "mkdocs"
    ports:
      - "8000:8000"
    command: ["serve", "--dev-addr=0.0.0.0:8000"]

  mike:
    <<: *mkdocs
    entrypoint: "mike"

  bump:
    <<: *devbox
    <<: *mount-app-and-user-git-config
    entrypoint: docker/bump_version.sh
